name: "running unit test, build docker image"
on:
  push:
    branches:
      - "master"
jobs:
  unit-test:
    name: "unit test"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - name: setup go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.2
      - name: running unit test
        run: go test ./... -cover

  build-push-docker:
    name: "build image and push registry dockerhub"
    runs-on: ubuntu-latest
    needs: unit-test
    steps:
      - uses: actions/checkout@v2
      - name: add .env
        env :
         ENV: ${{secrets.ENV}}
        run : echo "$ENV" > .env
      - name: build image
        run: docker build -t rizamahard/ofspace .
      - name: login dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: push image to dockerhub
        run: docker push rizamahard/ofspace:latest

  deployment:
    name: "deploy to ec2"
    runs-on: ubuntu-latest
    needs: build-push-docker
    steps:
      - uses: actions/checkout@v2
      - name: configuration ssh
        env:
          SSH_USER: ${{ secrets.SSH_USERNAME }}
          SSH_KEY: ${{ secrets.OFSPACE_PEM }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/ofspace.pem
          chmod 700 ~/.ssh/ofspace.pem
          cat >> ~/.ssh/config << END
          Host development 
            HostName $SSH_HOST
            User  $SSH_USER
            IdentityFile ~/.ssh/ofspace.pem
            StrictHostKeyChecking=no
          END
      - name: connect to ec2 AWS, remove container before pull, pull from registry, start
        run: ssh development 'sudo docker rm ofspace $(docker ps -a -q) || true && docker pull rizamahard/ofspace:latest && docker run -d -p 8080:8080 --name ofspace rizamahard/ofspace:latest'